accueil:
    path: /
    controller: App\Controller\DefaultController::index

contact:
    path: /contact
    controller: App\Controller\DefaultController::contact

categorieslug:
    path: /categorie/$slug
    controller: App\Controller\DefaultController::categorieslug
